#!/usr/bin/env python

import subprocess
import sys
import os

def main():
    outstanding_changes = subprocess.check_output(['git', 'status', '--porcelain'])
    if outstanding_changes:
        confirm_continue()
    current_branch = determine_current_branch()
    personal_remote = determine_personal_remote()
    push_to_personal(personal_remote, current_branch)
    target_branch = determine_pull_target()
    make_pull_request(target_branch)


def confirm_continue():
    confirm = raw_input('There are outstanding changes. Continue? [Yn]')
    if confirm and confirm.lower() == 'n':
        sys.exit(1)
    elif confirm and confirm.lower() != 'y':
        print "I don't know what you mean by '%s'" % confirm
        confirm_continue()

def determine_current_branch():
    return subprocess.check_output(['git', 'name-rev', '--name-only', 'HEAD'])

def determine_personal_remote():
    return os.environ['USER']

def push_to_personal(remote, branch):
    pass

def determine_pull_target():
    pass

def make_pull_request(target_branch):
    pass

main()
